/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package br.com.letscode;

import com.opencsv.CSVReader;
import com.opencsv.CSVReaderBuilder;
import com.opencsv.exceptions.CsvException;

import java.io.*;
import java.nio.file.Files;
import java.nio.file.Paths;
import java.time.LocalDateTime;
import java.util.*;

import java.math.BigDecimal;

public class App {

    public static void main(String[] args) throws IOException, CsvException {

        HashMap<String, Conta> contas = new HashMap<String, Conta>();

        Reader reader = Files.newBufferedReader(Paths.get("operacoes.csv"));
        CSVReader csvReader = new CSVReaderBuilder(reader).withSkipLines(1).build();

        List<String[]> operacoesList = csvReader.readAll();
        for (String[] operacao : operacoesList) {
            if (!contas.containsKey(operacao[1])) {
                contas.put(operacao[1], new Conta(operacao[1], operacao[4], operacao[3], operacao[2], new ArrayList<Operacao>(), BigDecimal.valueOf(0)));
            }

            contas.get(operacao[1]).getOperacoes().add(new Operacao(LocalDateTime.parse(operacao[0]), operacao[1], operacao[5], operacao[6], new BigDecimal(operacao[7])));

        }

        contas.entrySet().stream().map(Map.Entry::getValue).forEach(conta -> imprimirExtrato(conta.getId_da_conta(), conta.gerarExtrato()));

        //imprimirExtrato("148972c2-7062-40c3-9b4d-e96b538a90dc", contas.get("148972c2-7062-40c3-9b4d-e96b538a90dc").gerarExtrato());
        //System.out.println(contas.get("148972c2-7062-40c3-9b4d-e96b538a90dc").gerarExtrato());

    }

    public static void imprimirExtrato(String filename, String extrato) {

        try {
            FileWriter writer = new FileWriter("extratos/" + filename + ".txt");
            BufferedWriter bwr = new BufferedWriter(writer);
            bwr.write(extrato);
            bwr.close();
            System.out.println("Extrato gravado");

        } catch (IOException ioe) {
            ioe.printStackTrace();
        }
    }


}


